[package]
name = "hippo-swap"
version = "0.0.1"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "1e190630ff84510e4b37c8de3f5d74420d6225e3" }
MoveNursery = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/move-stdlib/nursery/", rev = "main" }

[addresses]
HippoSwap = "0xCAFE"
HippoSwapAdmin = "0xCAFF"